import type { Metadata } from "next";

import { Stack } from "@/src/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Stack justify="center" align="center" className="w-screen h-screen bg-primary">
        <Stack className="w-full max-w-md mx-auto">
            {children}
        </Stack>
    </Stack>
  );
}
